version: "3.7"

services:

  users:
    container_name: users
    hostname: users
    build:
      context: ./Users/Users.API
      dockerfile: Dockerfile
    environment:
      identityUrl: http://localhost:3000
      identityUrlInternal: http://identity
      ConnectionString: Host=postgreSql;Database=Users;Username=db_user;Password=db_pass
      validIssuers__0: http://identity
      validIssuers__1: http://localhost:3000
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_HTTPS_PORT: 5101
      ASPNETCORE_Kestrel__Certificates__Default__Password: qwerty1234
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/users.pfx
    ports:
      - 5101:443
    volumes:
      - ./certs/users.pfx:/https/users.pfx
