version: "3.7"

services:

  users-unit-tests:
    image: users-unit-tests:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./Users/Users.API/Dockerfile
      target: unittests
      args:
        GPR_NuGet_Passwd: ${GPR_NuGet_Passwd}
    volumes:
      - ./TestResult:/tests
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/users-unit-tests.trx
