version: "3.7"

services:

  rabbitmq:
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: usr
      RABBITMQ_DEFAULT_PASS: pwd
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit-mnesia:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq

  postgreSql:
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_LISTEN_PORT: 15432
      PGADMIN_DEFAULT_EMAIL: login
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 15432:15432
    volumes:
      - pgAdmin-data:/var/lib/pgadmin

  redis:
    ports:
      - 6379:6379

  users:
    environment:
      identityUrl: http://localhost:3000
      identityUrlInternal: http://identity
      ConnectionString: Host=postgreSql;Database=Users;Username=db_user;Password=db_pass
      ASPNETCORE_URLS: https://+:5101
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: qwerty1234
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/users.pfx
      Serilog__WriteTo__1__Args__requestUri: http://logstash:8080
    ports:
      - 5101:5101
    volumes:
      - ./certs/users.pfx:/https/users.pfx

  orders:
    environment:
      identityUrl: http://localhost:3000
      identityUrlInternal: http://identity
      ConnectionString: Host=postgreSql;Database=Orders;Username=db_user;Password=db_pass
      rabbitMQHostName: rabbitmq
      rabbitMQUserName: usr
      rabbitMQPassword: pwd
      ASPNETCORE_URLS: https://+:5201
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: qwerty1234
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/orders.pfx
      Serilog__WriteTo__1__Args__requestUri: http://logstash:8080
    ports:
      - 5201:5201
    volumes:
      - ./certs/orders.pfx:/https/orders.pfx

  bff:
    environment:
      identityUrl: http://localhost:3000
      identityUrlInternal: http://identity
      redisConfig: redis
      clients__scopes: users orders
      clients__users__baseUrl: https://users:5101
      clients__orders__baseUrl: https://orders:5201
      origins__0: https://localhost:1443
      origins__1: http://localhost:4200
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: qwerty1234
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      Serilog__WriteTo__1__Args__requestUri: http://logstash:8080
    ports:
      - 5001:5001
    volumes:
      - ./certs/localhost.pfx:/https/localhost.pfx

  identity:
    build:
      context: ./Auth/Identity
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      issuerUri: http://identity
    ports:
      - 3000:80

  bff_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/localhost.crt:/etc/nginx/localhost.crt
      - ./certs/localhost.pem:/etc/nginx/localhost.key
    ports:
      - 1443:443
    depends_on:
      - bff
      - identity

  web:
    image: web:${WEB_TAG:-latest}
    build:
      context: ./Web
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - bff

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
     - 5601:5601
    depends_on:
     - elasticsearch
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    ports:
      - 8080:8080
    volumes:
      - ./elk/logstash.log.conf:/usr/share/logstash/pipeline/logstash.log.conf


volumes:
  rabbit-mnesia:
  postgres-data:
  pgAdmin-data:
  elasticsearch-data:
