version: "3.7"

services:

  rabbitmq:
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: usr
      RABBITMQ_DEFAULT_PASS: pwd
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit-mnesia:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq

  postgreSql:
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_LISTEN_PORT: 15432
      PGADMIN_DEFAULT_EMAIL: login
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 15432:15432
    volumes:
      - pgAdmin-data:/var/lib/pgadmin

  redis:
    ports:
      - 6379:6379

  redis-event-bus:
    ports:
      - 6380:6379

  users:
    environment:
      identityUrl: https://localhost:3001
      identityUrlInternal: https://identity:3001
      ConnectionString: Host=postgreSql;Database=Users;Username=db_user;Password=db_pass
      ASPNETCORE_URLS: https://+:5101
      ASPNETCORE_ENVIRONMENT: Development
      Kestrel__Certificates__Default__Password: qwerty1234
      Kestrel__Certificates__Default__Path: /https/users.pfx
    ports:
      - 5101:5101
    volumes:
      - ./certs/users.pfx:/https/users.pfx

  orders:
    environment:
      identityUrl: https://localhost:3001
      identityUrlInternal: https://identity:3001
      ConnectionString: Host=postgreSql;Database=Orders;Username=db_user;Password=db_pass
      #RabbitMQ__Connection__HostName: rabbitmq
      #RabbitMQ__Connection__VirtualHost: /
      #RabbitMQ__Connection__UserName: usr
      #RabbitMQ__Connection__Password: pwd
      #RabbitMQ__Connection__ConnectRetryAttempts: 3
      #RabbitMQ__EventBus__ExchangeName: microservices
      #RabbitMQ__EventBus__QueueName: orders
      RedisEventBus__Configuration: localhost:6380
      RedisEventBus__ConsumerGroupName: Orders
      RedisEventBus__ConsumerName: orders-consumer
      RedisEventBus__BatchPerGroupSize: 5
      ASPNETCORE_URLS: https://+:5201
      ASPNETCORE_ENVIRONMENT: Development
      Kestrel__Certificates__Default__Password: qwerty1234
      Kestrel__Certificates__Default__Path: /https/orders.pfx
    ports:
      - 5201:5201
    volumes:
      - ./certs/orders.pfx:/https/orders.pfx

  bff:
    environment:
      identityUrl: https://localhost:3001
      identityUrlInternal: https://identity:3001
      redisConfig: redis
      clients__scopes: users orders
      clients__users__baseUrl: https://users:5101
      clients__orders__baseUrl: https://orders:5201
      origins__0: https://localhost:1443
      origins__1: https://localhost:4201
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_ENVIRONMENT: Development
      Kestrel__Certificates__Default__Password: qwerty1234
      Kestrel__Certificates__Default__Path: /https/bff.pfx
    ports:
      - 5001:5001
    volumes:
      - ./certs/bff.pfx:/https/bff.pfx

  identity:
    build:
      context: ./Auth/Identity
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: https://+:3001
      ASPNETCORE_ENVIRONMENT: Development
      Kestrel__Certificates__Default__Password: qwerty1234
      Kestrel__Certificates__Default__Path: /https/identity.pfx
      issuerUri: https://identity:3001
    ports:
      - 3001:3001
    volumes:
      - ./certs/identity.pfx:/https/identity.pfx 

  bff_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/bff_proxy.crt:/etc/nginx/bff_proxy.crt
      - ./certs/bff_proxy.pem:/etc/nginx/bff_proxy.key
    ports:
      - 1443:443
    depends_on:
      - bff
      - identity

  web:
    image: web:${WEB_TAG:-latest}
    build:
      context: ./Web
      dockerfile: Dockerfile
    volumes:
      - ./certs/web.crt:/etc/nginx/web.crt
      - ./certs/web.pem:/etc/nginx/web.key
    ports:
      - 4201:443
    depends_on:
      - bff

volumes:
  rabbit-mnesia:
  postgres-data:
  pgAdmin-data:
