version: "3.7"

services:

  orders:
    container_name: orders
    image: orders:${TAG:-latest}
    hostname: orders
    build:
      context: ./
      dockerfile: ./Orders/Orders.API/Dockerfile
      args:
        GPR_NuGet_Passwd: ${GPR_NuGet_Passwd}
    environment:
      identityUrl: http://localhost:3000
      identityUrlInternal: http://identity
      ConnectionString: Host=postgreSql;Database=Orders;Username=db_user;Password=db_pass
      validIssuers__0: http://identity
      validIssuers__1: http://localhost:3000
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: qwerty1234
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/orders.pfx
    ports:
      - 5201:443
    volumes:
      - ./certs/orders.pfx:/https/orders.pfx
