version: "3.7"

services:

  rabbit:
    image: rabbitmq:management
    container_name: rabbit-main
    hostname: rabbitmq-main
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit-mnesia:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-main

  postgreSql:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    environment:
      PGADMIN_LISTEN_PORT: 15432
      PGADMIN_DEFAULT_EMAIL: login
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 15432:15432
    volumes:
      - pgAdmin-data:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: redisCache
    hostname: redis
    ports:
      - 6379:6379

volumes:
  rabbit-mnesia:
  postgres-data:
  pgAdmin-data:
  