version: "3.7"

services:

  #rabbitmq:
  # image: rabbitmq:management

  postgreSql:
    image: postgres:latest

  redis:
    image: redis:latest

  redis-event-bus:
    image: redis:latest

  users:
    image: users:${USERS_TAG:-latest}
    build:
      context: ./
      dockerfile: ./Users/Users.API/Dockerfile
      #args:
        #GPR_NuGet_Passwd: ${GPR_NuGet_Passwd}
    depends_on:
      - postgreSql

  orders:
    image: orders:${ORDERS_TAG:-latest}
    build:
      context: ./
      dockerfile: ./Orders/Orders.API/Dockerfile
      #args:
        #GPR_NuGet_Passwd: ${GPR_NuGet_Passwd}
    depends_on:
      - postgreSql
      #- rabbitmq
      - redis-event-bus

  bff:
    image: bff:${BFF_TAG:-latest}
    build:
      context: ./
      dockerfile: ./BFF/Dockerfile
      #args:
        #GPR_NuGet_Passwd: ${GPR_NuGet_Passwd}
    depends_on:
      - postgreSql
      - redis
      - users
      - orders
