version: "3.7"

services:

  bff:
    container_name: bff
    image: bff:${TAG:-latest}
    hostname: bff
    build:
      context: ./
      dockerfile: ./BFF/Dockerfile
      args:
        GPR_NuGet_Passwd: ${GPR_NuGet_Passwd}
    environment:
      identityUrl: http://localhost:3000
      identityUrlInternal: http://identity
      ASPNETCORE_ENVIRONMENT: Development
      redisConfig: redis
      clients__scopes: users orders
      clients__users__baseUrl: https://users
      clients__orders__baseUrl: https://orders
      validIssuers__0: http://identity
      validIssuers__1: http://localhost:3000
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: qwerty1234
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
    ports:
      - 5001:443
    volumes:
      - ./certs/localhost.pfx:/https/localhost.pfx
